// src/life/choreography/manifest.js — authoritative index of every authored choreography program.
// Each entry mirrors the JSON metadata; tags are generous synonyms for command matching.

export const MOTION_MANIFEST = [
  // ── existing library ──────────────────────────────────────────────────────
  {
    id: 'wave',
    kind: 'gesture',
    tags: ['wave', 'hello', 'goodbye', 'greet', 'farewell', 'hand wave'],
    desc: 'Wave the right hand in greeting or farewell.',
  },
  {
    id: 'nervous_glance',
    kind: 'emote',
    tags: ['nervous', 'glance', 'look', 'anxious', 'shifty', 'wary', 'glancing'],
    desc: 'Dart the gaze left and right in a nervous, wary glance.',
  },
  {
    id: 'sit_down',
    kind: 'sit',
    tags: ['sit', 'sit down', 'seated', 'chair', 'bench', 'rest', 'sitting'],
    desc: 'Lower into a sitting position — terminal sit state.',
  },
  {
    id: 'dance_improvised',
    kind: 'dance',
    tags: ['dance', 'improvise', 'groove', 'move', 'sway', 'freestyle', 'dancing'],
    desc: 'Improvise a short dance with swinging arms and a swaying spine.',
  },

  // ── new library ───────────────────────────────────────────────────────────
  {
    id: 'jumping_jacks',
    kind: 'jump',
    tags: ['jumping', 'jacks', 'exercise', 'star', 'jumps', 'jumping jacks', 'cardio'],
    desc: 'Three repetitions of jumping jacks — arms swept out and up while legs spread, then return.',
  },
  {
    id: 'handstand',
    kind: 'gesture',
    tags: ['handstand', 'invert', 'upside down', 'balance', 'acrobat', 'gymnastics'],
    desc: 'Kick up into a handstand — arms overhead, legs inverted — then return to standing.',
  },
  {
    id: 'headstand',
    kind: 'gesture',
    tags: ['headstand', 'invert', 'upside down', 'head balance', 'gymnastics', 'yoga'],
    desc: 'Lower into a headstand with forearms on the ground, legs vertical, then return to standing.',
  },
  {
    id: 'cartwheel_prep',
    kind: 'gesture',
    tags: ['cartwheel', 'prep', 'side bend', 'warmup', 'gymnastics', 'acrobat', 'stretch'],
    desc: 'Reach arms overhead and side-bend in preparation for a cartwheel, then return to standing.',
  },
  {
    id: 'pushup',
    kind: 'gesture',
    tags: ['pushup', 'push up', 'exercise', 'strength', 'arms', 'chest', 'floor'],
    desc: 'Three push-up repetitions — lower the body by bending elbows then press back up.',
  },
  {
    id: 'situp',
    kind: 'gesture',
    tags: ['situp', 'sit up', 'exercise', 'core', 'abs', 'crunch', 'floor'],
    desc: 'Three sit-up repetitions from a lying position — curling the spine upward then back down.',
  },
  {
    id: 'squat',
    kind: 'gesture',
    tags: ['squat', 'squatting', 'exercise', 'legs', 'lower body', 'strength', 'bend'],
    desc: 'Three squat repetitions — bend the knees into a low squat then stand back up.',
  },
  {
    id: 'lunge',
    kind: 'gesture',
    tags: ['lunge', 'lunging', 'exercise', 'legs', 'stretch', 'step forward', 'strength'],
    desc: 'Step forward into a lunge — front knee bent, rear leg extended — then return to standing.',
  },
  {
    id: 'plank',
    kind: 'gesture',
    tags: ['plank', 'planking', 'core', 'exercise', 'hold', 'push up position', 'strength'],
    desc: 'Hold a plank position with straight arms and body, then return to standing.',
  },
  {
    id: 'stretch_arms',
    kind: 'gesture',
    tags: ['stretch', 'arms', 'reach', 'overhead', 'extension', 'warm up', 'flexibility'],
    desc: 'Raise both arms overhead and stretch upward, then lower back to rest.',
  },
  {
    id: 'toe_touch',
    kind: 'gesture',
    tags: ['toe touch', 'touch toes', 'bend', 'forward fold', 'hamstring', 'stretch', 'flexibility'],
    desc: 'Bend forward to touch the toes — arms reaching down — then stand back up.',
  },
  {
    id: 'bow',
    kind: 'gesture',
    tags: ['bow', 'bowing', 'respect', 'greeting', 'nod', 'curtsy', 'formal'],
    desc: 'Bow forward at the waist as a gesture of respect, then straighten up.',
  },
  {
    id: 'curtsy',
    kind: 'gesture',
    tags: ['curtsy', 'curtsey', 'bow', 'respect', 'greeting', 'formal', 'reverence'],
    desc: 'Perform a curtsy — one knee dips while arms extend gracefully — then return upright.',
  },
  {
    id: 'salute',
    kind: 'gesture',
    tags: ['salute', 'military', 'greeting', 'respect', 'hand to forehead', 'formal'],
    desc: 'Raise the right hand to the forehead in a crisp military salute, then lower.',
  },
  {
    id: 'clap',
    kind: 'gesture',
    tags: ['clap', 'clapping', 'applaud', 'applause', 'happy', 'cheer', 'hands'],
    desc: 'Clap hands together three times in front of the chest, then lower arms.',
  },
  {
    id: 'cheer',
    kind: 'gesture',
    tags: ['cheer', 'cheering', 'celebrate', 'victory', 'arms up', 'hooray', 'excitement'],
    desc: 'Throw both arms up in celebration with a cheer, then lower them back down.',
  },
  {
    id: 'point_forward',
    kind: 'gesture',
    tags: ['point', 'pointing', 'forward', 'direct', 'indicate', 'finger', 'gesture'],
    desc: 'Extend the right arm forward to point at something, then lower the arm.',
  },
  {
    id: 'beckon',
    kind: 'gesture',
    tags: ['beckon', 'come here', 'wave in', 'signal', 'invite', 'hand gesture', 'summon'],
    desc: 'Extend an arm and curl the hand inward to beckon someone closer, repeated twice.',
  },
  {
    id: 'shrug',
    kind: 'gesture',
    tags: ['shrug', 'shrugging', 'dunno', 'unsure', 'confused', 'shoulders', 'gesture'],
    desc: 'Raise both shoulders with palms up in a classic shrug, then relax.',
  },
  {
    id: 'nod',
    kind: 'gesture',
    tags: ['nod', 'nodding', 'yes', 'agree', 'acknowledge', 'head nod', 'affirmative'],
    desc: 'Nod the head forward and back twice to indicate agreement.',
  },
  {
    id: 'shake_head',
    kind: 'gesture',
    tags: ['shake head', 'no', 'disagree', 'refuse', 'negative', 'head shake', 'denial'],
    desc: 'Shake the head side to side twice to indicate disagreement or refusal.',
  },
  {
    id: 'facepalm',
    kind: 'gesture',
    tags: ['facepalm', 'face palm', 'embarrassed', 'disbelief', 'oh no', 'reaction', 'palm face'],
    desc: 'Raise a hand to cover the face in an exasperated facepalm, then lower.',
  },
  {
    id: 'flex',
    kind: 'gesture',
    tags: ['flex', 'flexing', 'muscles', 'show off', 'bicep', 'strong', 'pose'],
    desc: 'Flex both biceps by raising and bending the arms in a muscle-man pose, then lower.',
  },
  {
    id: 'taunt',
    kind: 'gesture',
    tags: ['taunt', 'taunting', 'mock', 'challenge', 'provoke', 'neener', 'gesture'],
    desc: 'Wiggle fingers at the sides of the head in a playful taunt, then return arms down.',
  },
  {
    id: 'wave_both',
    kind: 'gesture',
    tags: ['wave both', 'both hands', 'wave', 'greeting', 'farewell', 'hello', 'goodbye'],
    desc: 'Wave both arms overhead in a big greeting or farewell gesture.',
  },
  {
    id: 'kneel',
    kind: 'gesture',
    tags: ['kneel', 'kneeling', 'bow', 'reverence', 'humble', 'ground', 'down'],
    desc: 'Lower to one knee in a kneeling position, then rise back to standing.',
  },
  {
    id: 'pray',
    kind: 'gesture',
    tags: ['pray', 'prayer', 'praying', 'hands together', 'worship', 'meditate', 'reverence'],
    desc: 'Press hands together in a prayer pose with a slight bow of the head.',
  },
  {
    id: 'lie_down_back',
    kind: 'sleep',
    tags: ['lie down', 'lying', 'back', 'rest', 'sleep', 'horizontal', 'supine'],
    desc: 'Lie down on the back — legs extending flat, arms at sides — a terminal resting pose.',
  },
  {
    id: 'lie_down_belly',
    kind: 'sleep',
    tags: ['lie down', 'belly', 'prone', 'face down', 'floor', 'rest', 'sleep'],
    desc: 'Lie down on the belly — legs flat, arms bent beside the chest — a terminal prone rest pose.',
  },
  {
    id: 'crawl',
    kind: 'gesture',
    tags: ['crawl', 'crawling', 'hands knees', 'floor', 'baby', 'low', 'creep'],
    desc: 'Get down on hands and knees for a crawling pose, then return to standing.',
  },
  {
    id: 'roll_over',
    kind: 'gesture',
    tags: ['roll over', 'roll', 'tumble', 'barrel roll', 'floor', 'ground', 'acrobat'],
    desc: 'Tuck and roll to one side along the ground, then return to standing.',
  },
  {
    id: 'jump_in_place',
    kind: 'jump',
    tags: ['jump', 'jumping', 'in place', 'leap', 'hop', 'bounce', 'exercise'],
    desc: 'Jump straight up in place three times — crouch down and spring up.',
  },
  {
    id: 'hop_left',
    kind: 'jump',
    tags: ['hop left', 'hop', 'left', 'jump', 'step left', 'lateral', 'move'],
    desc: 'Hop to the left — lift the right foot and push off left, then land.',
  },
  {
    id: 'hop_right',
    kind: 'jump',
    tags: ['hop right', 'hop', 'right', 'jump', 'step right', 'lateral', 'move'],
    desc: 'Hop to the right — lift the left foot and push off right, then land.',
  },
  {
    id: 'spin_around',
    kind: 'dance',
    tags: ['spin', 'spin around', 'turn', 'rotate', 'twirl', 'pirouette', 'dance'],
    desc: 'Spin in a full circle with arms extended, then come to a stop.',
  },
  {
    id: 'moonwalk',
    kind: 'dance',
    tags: ['moonwalk', 'moon walk', 'dance', 'slide', 'michael jackson', 'cool', 'backward'],
    desc: 'Perform a moonwalk-style glide — alternating leg lifts while arms swing — then stop.',
  },
  {
    id: 'march_in_place',
    kind: 'gesture',
    tags: ['march', 'marching', 'in place', 'walk', 'step', 'military', 'parade'],
    desc: 'March in place with exaggerated knee lifts and swinging arms.',
  },
  {
    id: 'tiptoe',
    kind: 'gesture',
    tags: ['tiptoe', 'tiptoeing', 'sneak', 'quiet', 'careful', 'stealth', 'soft steps'],
    desc: 'Rise onto tiptoes with arms slightly raised for balance, then lower quietly.',
  },
  {
    id: 'crouch',
    kind: 'gesture',
    tags: ['crouch', 'crouching', 'duck', 'low', 'hide', 'avoid', 'stealth'],
    desc: 'Drop into a low crouch with bent knees and forward lean, then stand.',
  },
  {
    id: 'look_around',
    kind: 'gesture',
    tags: ['look around', 'scan', 'survey', 'observe', 'check', 'awareness', 'watch'],
    desc: 'Turn the head left then right to look around, combined with a slight spine twist.',
  },
  {
    id: 'yawn_stretch',
    kind: 'gesture',
    tags: ['yawn', 'stretch', 'tired', 'sleepy', 'morning', 'wake up', 'arms overhead'],
    desc: 'Yawn with mouth open and stretch both arms overhead, then relax.',
  },
  {
    id: 'dig',
    kind: 'gesture',
    tags: ['dig', 'digging', 'shovel', 'earth', 'soil', 'work', 'labor'],
    desc: 'Swing arms in a digging motion — driving a tool into the ground and levering up earth.',
  },
  {
    id: 'hammer',
    kind: 'gesture',
    tags: ['hammer', 'hammering', 'pound', 'nail', 'strike', 'craft', 'work', 'build'],
    desc: 'Raise a hammer overhead and bring it down in three striking motions.',
  },
  {
    id: 'chop_motion',
    kind: 'gesture',
    tags: ['chop', 'chopping', 'axe', 'wood', 'cut', 'swing', 'lumber', 'strike'],
    desc: 'Swing both arms in a chopping motion as if splitting wood — raise and bring down twice.',
  },
  {
    id: 'sweep',
    kind: 'gesture',
    tags: ['sweep', 'sweeping', 'broom', 'clean', 'floor', 'push', 'work', 'chore'],
    desc: 'Sweep the floor with side-to-side arm movements, bending slightly at the waist.',
  },
  {
    id: 'fish_cast',
    kind: 'gesture',
    tags: ['fish', 'cast', 'fishing', 'rod', 'throw', 'line', 'water', 'catch'],
    desc: 'Cast a fishing line — reach back then sweep forward with the rod arm.',
  },
];
