"""Create biome layer stack JSON files for all 18 biomes."""
import json, os

OUTDIR = "data/terrain_objects/biome_layers"
os.makedirs(OUTDIR, exist_ok=True)

BIOMES = {
    "grassland": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"dirt_patch","weight":0.6,"variant_count":64},
            {"object_id":"dry_soil","weight":0.3,"variant_count":32},
            {"object_id":"dark_earth","weight":0.1,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"pebble","weight":0.3,"variant_count":64},
            {"object_id":"dry_leaf","weight":0.25,"variant_count":32},
            {"object_id":"twig","weight":0.2,"variant_count":16},
            {"object_id":"small_stone","weight":0.15,"variant_count":32},
            {"object_id":"seed_pod","weight":0.1,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.25]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"short_grass","weight":0.35,"variant_count":64},
            {"object_id":"tall_grass","weight":0.25,"variant_count":64},
            {"object_id":"meadow_grass","weight":0.2,"variant_count":32},
            {"object_id":"clover_patch","weight":0.1,"variant_count":16},
            {"object_id":"grass_tuft","weight":0.1,"variant_count":32}
        ],"z_offset":2,"scale_range":[0.4,0.9]},
        {"layer":4,"name":"accent_flora","coverage":0.15,"objects":[
            {"object_id":"wildflower","weight":0.3,"variant_count":32},
            {"object_id":"daisy","weight":0.2,"variant_count":16},
            {"object_id":"dandelion","weight":0.2,"variant_count":16},
            {"object_id":"poppy","weight":0.15,"variant_count":16},
            {"object_id":"flowering_bush","weight":0.15,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.25,0.45]},
        {"layer":5,"name":"large_objects","coverage":0.02,"cluster_mode":"grouped","cluster_size":[3,8],"cluster_spacing":[15,40],"objects":[
            {"object_id":"oak_tree","weight":0.35,"variant_count":16},
            {"object_id":"birch_tree","weight":0.25,"variant_count":16},
            {"object_id":"flowering_bush","weight":0.2,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.1,"variant_count":8},
            {"object_id":"fallen_log","weight":0.1,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "forest": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"forest_floor","weight":0.5,"variant_count":64},
            {"object_id":"leaf_litter","weight":0.3,"variant_count":32},
            {"object_id":"root_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"autumn_leaves","weight":0.3,"variant_count":32},
            {"object_id":"bark_chip","weight":0.25,"variant_count":16},
            {"object_id":"twig","weight":0.2,"variant_count":16},
            {"object_id":"acorn","weight":0.15,"variant_count":8},
            {"object_id":"pine_cone","weight":0.1,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"forest_fern","weight":0.3,"variant_count":32},
            {"object_id":"ground_moss","weight":0.35,"variant_count":64},
            {"object_id":"short_grass","weight":0.2,"variant_count":32},
            {"object_id":"climbing_vine","weight":0.15,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.4,0.7]},
        {"layer":4,"name":"accent_flora","coverage":0.2,"objects":[
            {"object_id":"toadstool","weight":0.3,"variant_count":16},
            {"object_id":"morel","weight":0.2,"variant_count":16},
            {"object_id":"wildflower","weight":0.2,"variant_count":16},
            {"object_id":"spider_web","weight":0.15,"variant_count":8},
            {"object_id":"bracket_fungus","weight":0.15,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.2,0.4]},
        {"layer":5,"name":"large_objects","coverage":0.04,"cluster_mode":"grouped","cluster_size":[4,12],"cluster_spacing":[10,30],"objects":[
            {"object_id":"oak_tree","weight":0.3,"variant_count":16},
            {"object_id":"birch_tree","weight":0.2,"variant_count":16},
            {"object_id":"maple_tree","weight":0.15,"variant_count":8},
            {"object_id":"elm_tree","weight":0.1,"variant_count":8},
            {"object_id":"fallen_log","weight":0.15,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.1,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "taiga": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"pine_needle_bed","weight":0.6,"variant_count":64},
            {"object_id":"frozen_soil","weight":0.25,"variant_count":32},
            {"object_id":"bark_debris","weight":0.15,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"pine_cone","weight":0.3,"variant_count":16},
            {"object_id":"twig","weight":0.25,"variant_count":16},
            {"object_id":"frozen_leaf","weight":0.25,"variant_count":16},
            {"object_id":"ice_crystal","weight":0.2,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"hardy_moss","weight":0.35,"variant_count":32},
            {"object_id":"ground_moss","weight":0.35,"variant_count":32},
            {"object_id":"frozen_grass","weight":0.3,"variant_count":32}
        ],"z_offset":2,"scale_range":[0.4,0.7]},
        {"layer":4,"name":"accent","coverage":0.1,"objects":[
            {"object_id":"packed_snow","weight":0.5,"variant_count":16},
            {"object_id":"toadstool","weight":0.3,"variant_count":8},
            {"object_id":"bear_den","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.3,0.6]},
        {"layer":5,"name":"large_objects","coverage":0.03,"cluster_mode":"grouped","cluster_size":[5,15],"cluster_spacing":[8,25],"objects":[
            {"object_id":"pine_tree","weight":0.3,"variant_count":16},
            {"object_id":"spruce_tree","weight":0.3,"variant_count":16},
            {"object_id":"fir_tree","weight":0.15,"variant_count":16},
            {"object_id":"cedar_tree","weight":0.1,"variant_count":8},
            {"object_id":"fallen_log","weight":0.1,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.05,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "desert": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"cracked_earth","weight":0.4,"variant_count":64},
            {"object_id":"desert_sand","weight":0.4,"variant_count":64},
            {"object_id":"sun_bleached_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"small_stone","weight":0.4,"variant_count":32},
            {"object_id":"bone_fragment","weight":0.2,"variant_count":8},
            {"object_id":"dried_seed","weight":0.2,"variant_count":8},
            {"object_id":"dune_ripple","weight":0.2,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"sparse_flora","coverage":0.3,"objects":[
            {"object_id":"dry_grass","weight":0.5,"variant_count":32},
            {"object_id":"desert_shrub","weight":0.3,"variant_count":8},
            {"object_id":"dead_twig","weight":0.2,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.3,0.6]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"cactus","weight":0.4,"variant_count":8},
            {"object_id":"desert_shrub","weight":0.3,"variant_count":8},
            {"object_id":"sandstone_boulder","weight":0.2,"variant_count":8},
            {"object_id":"bone_pile","weight":0.1,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.5,0.9]}
    ],
    "tundra": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"permafrost","weight":0.4,"variant_count":32},
            {"object_id":"frozen_gravel","weight":0.35,"variant_count":32},
            {"object_id":"packed_earth","weight":0.25,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"ice_shard","weight":0.35,"variant_count":16},
            {"object_id":"frozen_pebble","weight":0.35,"variant_count":16},
            {"object_id":"frost_crystal","weight":0.3,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"sparse_flora","coverage":0.4,"objects":[
            {"object_id":"frozen_grass","weight":0.4,"variant_count":32},
            {"object_id":"hardy_moss","weight":0.35,"variant_count":16},
            {"object_id":"lichen","weight":0.25,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.3,0.5]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"ice_formation","weight":0.4,"variant_count":8},
            {"object_id":"frozen_boulder","weight":0.4,"variant_count":8},
            {"object_id":"dead_shrub","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.5,0.8]}
    ],
    "volcanic": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"ash_layer","weight":0.4,"variant_count":32},
            {"object_id":"charred_earth","weight":0.35,"variant_count":32},
            {"object_id":"cooled_lava","weight":0.25,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"obsidian_shard","weight":0.35,"variant_count":16},
            {"object_id":"pumice_stone","weight":0.35,"variant_count":16},
            {"object_id":"sulfur_deposit","weight":0.3,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.15,0.3]},
        {"layer":3,"name":"sparse_flora","coverage":0.15,"objects":[
            {"object_id":"charred_grass","weight":0.5,"variant_count":8},
            {"object_id":"ember_patch","weight":0.3,"variant_count":8},
            {"object_id":"sulfur_vent","weight":0.2,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.3,0.5]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"charred_tree","weight":0.4,"variant_count":8},
            {"object_id":"volcanic_rock","weight":0.4,"variant_count":8},
            {"object_id":"lava_rock","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.6,1.0]}
    ],
    "swamp": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"swamp_mud","weight":0.5,"variant_count":64},
            {"object_id":"peat_bog","weight":0.3,"variant_count":16},
            {"object_id":"wet_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"wet_leaves","weight":0.4,"variant_count":32},
            {"object_id":"algae_patch","weight":0.35,"variant_count":16},
            {"object_id":"swamp_debris","weight":0.25,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.15,0.3]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"reed","weight":0.3,"variant_count":32},
            {"object_id":"cattail","weight":0.25,"variant_count":16},
            {"object_id":"ground_moss","weight":0.25,"variant_count":32},
            {"object_id":"bulrush","weight":0.2,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.4,0.7]},
        {"layer":4,"name":"accent_flora","coverage":0.2,"objects":[
            {"object_id":"toadstool","weight":0.35,"variant_count":8},
            {"object_id":"freshwater_algae","weight":0.35,"variant_count":8},
            {"object_id":"cocoon","weight":0.3,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.25,0.4]},
        {"layer":5,"name":"large_objects","coverage":0.03,"cluster_mode":"grouped","cluster_size":[3,6],"cluster_spacing":[12,30],"objects":[
            {"object_id":"mangrove_tree","weight":0.3,"variant_count":8},
            {"object_id":"dead_tree","weight":0.3,"variant_count":8},
            {"object_id":"hollow_log","weight":0.2,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.2,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "tropical_forest": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"jungle_floor","weight":0.5,"variant_count":64},
            {"object_id":"rich_dark_soil","weight":0.3,"variant_count":16},
            {"object_id":"decomposing_leaves","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"fallen_fruit","weight":0.3,"variant_count":16},
            {"object_id":"large_leaf","weight":0.35,"variant_count":16},
            {"object_id":"vine_debris","weight":0.35,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.15,0.3]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"forest_fern","weight":0.3,"variant_count":16},
            {"object_id":"tropical_grass","weight":0.3,"variant_count":32},
            {"object_id":"ground_moss","weight":0.2,"variant_count":16},
            {"object_id":"giant_fern","weight":0.2,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.5,0.8]},
        {"layer":4,"name":"accent_flora","coverage":0.25,"objects":[
            {"object_id":"cactus_flower","weight":0.3,"variant_count":16},
            {"object_id":"toadstool","weight":0.25,"variant_count":8},
            {"object_id":"ethereal_vine","weight":0.25,"variant_count":8},
            {"object_id":"hibiscus","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.3,0.5]},
        {"layer":5,"name":"large_objects","coverage":0.05,"cluster_mode":"grouped","cluster_size":[5,15],"cluster_spacing":[8,20],"objects":[
            {"object_id":"palm_tree","weight":0.25,"variant_count":16},
            {"object_id":"kapok_tree","weight":0.2,"variant_count":8},
            {"object_id":"jungle_tree","weight":0.25,"variant_count":16},
            {"object_id":"banana_tree","weight":0.15,"variant_count":8},
            {"object_id":"coconut_palm","weight":0.15,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "mountains": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"mountain_gravel","weight":0.5,"variant_count":64},
            {"object_id":"mountain_soil","weight":0.3,"variant_count":16},
            {"object_id":"scree","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"loose_stone","weight":0.4,"variant_count":32},
            {"object_id":"slate_chip","weight":0.35,"variant_count":16},
            {"object_id":"gravel_patch","weight":0.25,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.25]},
        {"layer":3,"name":"sparse_flora","coverage":0.25,"objects":[
            {"object_id":"arctic_poppy","weight":0.35,"variant_count":8},
            {"object_id":"hardy_moss","weight":0.35,"variant_count":16},
            {"object_id":"lichen","weight":0.3,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.2,0.4]},
        {"layer":4,"name":"large_objects","coverage":0.02,"objects":[
            {"object_id":"granite_boulder","weight":0.35,"variant_count":8},
            {"object_id":"cliff_face","weight":0.25,"variant_count":8},
            {"object_id":"cave_entrance","weight":0.15,"variant_count":8},
            {"object_id":"rock_overhang","weight":0.15,"variant_count":8},
            {"object_id":"eagle_nest","weight":0.1,"variant_count":4}
        ],"z_offset":3,"scale_range":[0.7,1.1]}
    ],
    "arctic": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"packed_snow","weight":0.5,"variant_count":32},
            {"object_id":"ice_patch","weight":0.3,"variant_count":16},
            {"object_id":"frozen_ground","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"ice_crystal","weight":0.4,"variant_count":16},
            {"object_id":"frost_pattern","weight":0.35,"variant_count":16},
            {"object_id":"frozen_pebble","weight":0.25,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"sparse_flora","coverage":0.15,"objects":[
            {"object_id":"frozen_grass","weight":0.4,"variant_count":16},
            {"object_id":"lichen","weight":0.3,"variant_count":8},
            {"object_id":"fresh_snow","weight":0.3,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.3,0.5]},
        {"layer":4,"name":"large_objects","coverage":0.005,"objects":[
            {"object_id":"crystal_cluster","weight":0.5,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.5,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.6,1.0]}
    ],
    "beach": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"beach_sand","weight":0.6,"variant_count":64},
            {"object_id":"wet_sand","weight":0.3,"variant_count":16},
            {"object_id":"shell_fragment","weight":0.1,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"shell_scatter","weight":0.4,"variant_count":32},
            {"object_id":"seaweed_bit","weight":0.3,"variant_count":8},
            {"object_id":"pebble","weight":0.3,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"sparse_flora","coverage":0.2,"objects":[
            {"object_id":"sea_grass","weight":0.4,"variant_count":16},
            {"object_id":"dune_ripple","weight":0.35,"variant_count":8},
            {"object_id":"driftwood","weight":0.25,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.3,0.5]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"driftwood","weight":0.5,"variant_count":8},
            {"object_id":"flat_rock","weight":0.3,"variant_count":8},
            {"object_id":"crab_burrow","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.5,0.8]}
    ],
    "savanna": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"cracked_earth","weight":0.5,"variant_count":32},
            {"object_id":"desert_sand","weight":0.3,"variant_count":32},
            {"object_id":"dry_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"dry_leaf","weight":0.35,"variant_count":16},
            {"object_id":"small_stone","weight":0.35,"variant_count":16},
            {"object_id":"seed_pod","weight":0.3,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"ground_flora","coverage":0.6,"objects":[
            {"object_id":"savanna_grass","weight":0.5,"variant_count":64},
            {"object_id":"dry_grass","weight":0.3,"variant_count":32},
            {"object_id":"tall_grass","weight":0.2,"variant_count":32}
        ],"z_offset":2,"scale_range":[0.5,0.9]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"dead_tree","weight":0.3,"variant_count":8},
            {"object_id":"termite_mound","weight":0.25,"variant_count":8},
            {"object_id":"dry_bush","weight":0.25,"variant_count":8},
            {"object_id":"flat_rock","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.8,1.1]}
    ],
    "steppe": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"cracked_earth","weight":0.5,"variant_count":32},
            {"object_id":"gravel_patch","weight":0.3,"variant_count":16},
            {"object_id":"dry_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"flat_rock","weight":0.4,"variant_count":16},
            {"object_id":"dried_plant","weight":0.35,"variant_count":8},
            {"object_id":"gravel_patch","weight":0.25,"variant_count":16}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"sparse_flora","coverage":0.5,"objects":[
            {"object_id":"short_grass","weight":0.5,"variant_count":32},
            {"object_id":"dry_grass","weight":0.3,"variant_count":16},
            {"object_id":"desert_shrub","weight":0.2,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.3,0.6]},
        {"layer":4,"name":"large_objects","coverage":0.01,"objects":[
            {"object_id":"flat_rock","weight":0.5,"variant_count":8},
            {"object_id":"dead_tree","weight":0.3,"variant_count":4},
            {"object_id":"dry_bush","weight":0.2,"variant_count":4}
        ],"z_offset":3,"scale_range":[0.5,0.8]}
    ],
    "mystic": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"mystic_ground","weight":0.5,"variant_count":64},
            {"object_id":"ethereal_soil","weight":0.3,"variant_count":16},
            {"object_id":"glowing_earth","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"crystal_fragment","weight":0.4,"variant_count":16},
            {"object_id":"glowing_particle","weight":0.35,"variant_count":16},
            {"object_id":"amethyst_geode","weight":0.25,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.1,0.25]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"ground_moss","weight":0.35,"variant_count":32},
            {"object_id":"glowing_mushroom","weight":0.35,"variant_count":16},
            {"object_id":"hardy_moss","weight":0.3,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.4,0.7]},
        {"layer":4,"name":"accent_flora","coverage":0.2,"objects":[
            {"object_id":"arcane_flower","weight":0.3,"variant_count":16},
            {"object_id":"spirit_wisp","weight":0.25,"variant_count":16},
            {"object_id":"runic_stone","weight":0.25,"variant_count":8},
            {"object_id":"ethereal_vine","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.25,0.45]},
        {"layer":5,"name":"large_objects","coverage":0.02,"objects":[
            {"object_id":"crystal_cluster","weight":0.35,"variant_count":8},
            {"object_id":"dead_tree","weight":0.35,"variant_count":8},
            {"object_id":"mist_pool","weight":0.15,"variant_count":8},
            {"object_id":"gem_deposit","weight":0.15,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.7,1.0]}
    ],
    "dense_forest": [
        {"layer":1,"name":"ground_texture","coverage":1.0,"objects":[
            {"object_id":"forest_floor","weight":0.5,"variant_count":64},
            {"object_id":"autumn_leaves","weight":0.3,"variant_count":32},
            {"object_id":"root_soil","weight":0.2,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"small_debris","coverage":1.0,"objects":[
            {"object_id":"autumn_leaves","weight":0.35,"variant_count":32},
            {"object_id":"bark_chip","weight":0.3,"variant_count":16},
            {"object_id":"twig","weight":0.35,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.1,0.2]},
        {"layer":3,"name":"ground_flora","coverage":1.0,"objects":[
            {"object_id":"forest_fern","weight":0.3,"variant_count":16},
            {"object_id":"ground_moss","weight":0.4,"variant_count":64},
            {"object_id":"climbing_vine","weight":0.3,"variant_count":16}
        ],"z_offset":2,"scale_range":[0.5,0.8]},
        {"layer":4,"name":"accent_flora","coverage":0.3,"objects":[
            {"object_id":"toadstool","weight":0.3,"variant_count":16},
            {"object_id":"bracket_fungus","weight":0.25,"variant_count":8},
            {"object_id":"spider_web","weight":0.25,"variant_count":8},
            {"object_id":"morel","weight":0.2,"variant_count":8}
        ],"z_offset":3,"scale_range":[0.2,0.4]},
        {"layer":5,"name":"large_objects","coverage":0.06,"cluster_mode":"grouped","cluster_size":[6,20],"cluster_spacing":[5,15],"objects":[
            {"object_id":"oak_tree","weight":0.25,"variant_count":16},
            {"object_id":"beech_tree","weight":0.2,"variant_count":8},
            {"object_id":"elm_tree","weight":0.15,"variant_count":8},
            {"object_id":"hollow_log","weight":0.15,"variant_count":8},
            {"object_id":"fallen_log","weight":0.15,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.1,"variant_count":8}
        ],"z_offset":4,"scale_range":[0.9,1.1]}
    ],
    "lake": [
        {"layer":1,"name":"underwater","coverage":1.0,"objects":[
            {"object_id":"freshwater_algae","weight":0.5,"variant_count":16},
            {"object_id":"pebble","weight":0.5,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"surface","coverage":0.4,"objects":[
            {"object_id":"reed","weight":0.35,"variant_count":16},
            {"object_id":"cattail","weight":0.35,"variant_count":8},
            {"object_id":"bulrush","weight":0.3,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.3,0.6]},
        {"layer":3,"name":"large_objects","coverage":0.05,"objects":[
            {"object_id":"fallen_log","weight":0.5,"variant_count":4},
            {"object_id":"mossy_boulder","weight":0.5,"variant_count":4}
        ],"z_offset":2,"scale_range":[0.5,0.8]}
    ],
    "river": [
        {"layer":1,"name":"riverbed","coverage":1.0,"objects":[
            {"object_id":"pebble","weight":0.5,"variant_count":16},
            {"object_id":"gravel_patch","weight":0.5,"variant_count":16}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"bank","coverage":0.3,"objects":[
            {"object_id":"reed","weight":0.4,"variant_count":16},
            {"object_id":"cattail","weight":0.3,"variant_count":8},
            {"object_id":"wet_leaves","weight":0.3,"variant_count":8}
        ],"z_offset":1,"scale_range":[0.3,0.6]},
        {"layer":3,"name":"large_objects","coverage":0.03,"objects":[
            {"object_id":"driftwood","weight":0.5,"variant_count":8},
            {"object_id":"mossy_boulder","weight":0.5,"variant_count":8}
        ],"z_offset":2,"scale_range":[0.6,0.9]}
    ],
    "ocean": [
        {"layer":1,"name":"seafloor","coverage":1.0,"objects":[
            {"object_id":"pebble","weight":0.6,"variant_count":16},
            {"object_id":"freshwater_algae","weight":0.4,"variant_count":8}
        ],"z_offset":0,"scale_range":[0.8,1.0]},
        {"layer":2,"name":"sea_objects","coverage":0.1,"objects":[
            {"object_id":"brain_coral","weight":0.3,"variant_count":8},
            {"object_id":"fan_coral","weight":0.35,"variant_count":8},
            {"object_id":"branching_coral","weight":0.35,"variant_count":4}
        ],"z_offset":1,"scale_range":[0.4,0.7]}
    ]
}

for biome_id, layers in BIOMES.items():
    data = {"biome_id": biome_id, "layers": layers}
    path = os.path.join(OUTDIR, biome_id + ".json")
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"{biome_id}: {len(layers)} layers")

print(f"\nCreated {len(BIOMES)} biome layer files in {OUTDIR}/")
