#!/usr/bin/env node
// scripts/asset-corpus/compile.mjs — registry/ -> out/counts.md + out/batches/*.json
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { enumerateRegistry, resolveDerived } from './lib/enumerate.mjs';
import { emitBatch, emitPilotBatch } from './lib/emit.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REG_DIR = join(HERE, 'registry');
const outIdx = process.argv.indexOf('--out');
const OUT = outIdx > -1 ? process.argv[outIdx + 1] : join(HERE, 'out');

const DATA_FILES = new Set(['biome_base_tiles.json']);
const byId = {};
for (const f of readdirSync(REG_DIR).filter((f) => f.endsWith('.json') && !DATA_FILES.has(f))) {
  const reg = JSON.parse(readFileSync(join(REG_DIR, f), 'utf8'));
  byId[reg.id] = reg;
}

mkdirSync(join(OUT, 'batches'), { recursive: true });

const lines = ['# Asset Corpus Enumeration', '', `Generated by compile.mjs — do not edit. Registry is the source.`, '',
  '| registry | plan | status | instances | base | states | anim jobs | total sprites |',
  '|---|---|---|---|---|---|---|---|'];
let grand = 0, grandAnim = 0;

for (const id of Object.keys(byId).sort()) {
  const reg = resolveDerived(byId[id], byId);
  const e = enumerateRegistry(reg);
  grand += e.totalSprites; grandAnim += e.animJobs;
  lines.push(`| ${e.id} | ${e.plan} | ${e.status} | ${e.instances ?? '—'} | ${e.baseSprites ?? '—'} | ${e.stateSprites ?? '—'} | ${e.animJobs ?? '—'} | ${e.totalSprites} |`);

  if (reg.status !== 'dormant') {
    const batch = emitBatch(byId[id], byId);
    writeFileSync(join(OUT, 'batches', `${batch.burst}.json`), JSON.stringify(batch, null, 2));
    if (byId[id].pilot) {
      const pilot = emitPilotBatch(byId[id], byId);
      writeFileSync(join(OUT, 'batches', `${pilot.burst}.json`), JSON.stringify(pilot, null, 2));
    }
  }
}

lines.push('', `**GRAND TOTAL: ${grand} sprites + ${grandAnim} animation jobs** (excluding open-ended runtime rows: discovered-recipe icons).`, '');
writeFileSync(join(OUT, 'counts.md'), lines.join('\n'));
console.log(`counts.md + batches written to ${OUT} — total ${grand} sprites, ${grandAnim} anim jobs`);
