// src/render/building-tiles.js — TILE-CORPUS wall renderer.
//
// Draws a building's SOUTH wall by MIRROR-tiling one base wall-tile per material (base·flip·base·flip…)
// across the footprint width, stacked per storey, with door/window OVERLAYS at the footprint's aperture
// tiles. The base tile (256px = 4 tiles wide × 4 tall @ 64px/tile, native alpha) is never modified, so
// walls are perfectly seamless + consistent. Routes through the same offscreen-canvas → GL scene FBO as
// the old wall path (drawBuildingTextured calls this, then the procedural roof). window._tileWalls flag.

import { WALL_CONFIG } from './wall-config.js';
import { buildingFloors } from './building-shadow.js';

const TILE_ROOT = '/assets/pixelab/buildings/tiles/';
const getDIR = (biome) => TILE_ROOT + (biome || 'grassland') + '/';
// Per-biome tile-material map: a building's world-gen wallSlug → tile-corpus FOLDER name. Desert's world-gen
// slugs differ from the folder names, so this also reconciles them (smooth_adobe→adobe, sandstone_block→
// sandstone, mudbrick_plaster→mudbrick, carved_rock→reed_palm). A biome ABSENT here is not tiled — its
// buildings keep the legacy procedural wall path.
const TILE_MATERIALS = {
  grassland: { timber_frame: 'timber_frame', fieldstone: 'fieldstone', cob: 'cob', wattle_daub: 'wattle_daub' },
  desert: { sandstone_block: 'sandstone', smooth_adobe: 'adobe', mudbrick_plaster: 'mudbrick', carved_rock: 'reed_palm' },
};
const BIOME_FALLBACK = { grassland: 'fieldstone', desert: 'adobe' };
const _img = new Map();
function img(url) { let im = _img.get(url); if (!im) { im = new Image(); im.src = url; _img.set(url, im); } return (im.complete && im.naturalWidth) ? im : null; }

// Animation frames (full wall-with-aperture tiles, one per swing step) generated by animate_object and
// stored at <material>/anim/<kind>/frame_NNN.png. The door PLAYS on player proximity: far = frame 0
// (closed), near = last frame (open). Returns the frame image (or null until that frame loads).
const ANIM_FRAMES = 9;
function animFrame(biome, mat, kind, idx) {
  return img(getDIR(biome) + mat + '/anim/' + kind + '/frame_' + String(idx).padStart(3, '0') + '.png');
}
// 0 (closed, player far) → 1 (open, player at the door). World-tile distance ramp.
function doorOpenAmount(b, d) {
  const p = (typeof window !== 'undefined') && window._player;
  if (!p || typeof p.x !== 'number') return 0;
  const dist = Math.hypot((b.x + d.x + 0.5) - p.x, (b.y + d.y + 0.5) - p.y);
  const R_OPEN = 4.0, R_FULL = 1.5;   // starts opening at 4 tiles, fully open within 1.5
  return Math.max(0, Math.min(1, (R_OPEN - dist) / (R_OPEN - R_FULL)));
}

// Resolve a building to its tile-corpus FOLDER name, or null if its biome isn't tiled (→ legacy wall path).
function materialOf(b) {
  if (typeof window !== 'undefined' && window._tileMaterial) return window._tileMaterial;
  const map = TILE_MATERIALS[b && b.biome];
  if (!map) return null;
  const s = ((b && b.wallSlug) || '').toLowerCase();
  return map[s] || BIOME_FALLBACK[b.biome] || null;
}
// Tile walls cover the biomes present in TILE_MATERIALS (grassland + desert). Gated by (biome, wallSlug) so
// every other biome keeps its own legacy wall path instead of inheriting grassland tiles.
export function isTiledBuilding(b) {
  if (typeof window !== 'undefined' && window._tileMaterial) return true; // console override forces it
  return !!materialOf(b);
}
export function tileMaterialReady(b) { const m = materialOf(b); return !!(m && img(getDIR(b && b.biome) + m + '/ground_plain__v0.png')); }
export function hasTileWall(b) {
  if (typeof window !== 'undefined' && window._tileWalls === false) return false;
  return isTiledBuilding(b) && tileMaterialReady(b);
}

// Footprint tile set in LOCAL 0-based coords (matching the renderer's b.x+local / footprint.doors[].x
// convention). The building's actual shape lives in footprint.sections (rect/L/T/courtyard/round/...).
function footprintSet(fp) {
  const set = new Set();
  for (const s of (fp.sections || [])) for (let y = s.y0; y < s.y0 + s.h; y++) for (let x = s.x0; x < s.x0 + s.w; x++) set.add(x + ',' + y);
  return set;
}
// SOUTH-FACING perimeter runs: contiguous spans of tiles whose south neighbour is OUTSIDE the footprint.
// Each run is one visible front-wall segment, so the renderer draws the building's TRUE outline (an L/T/
// round building's stepped front) instead of one bounding-box rectangle. Sorted north→south so nearer
// (front) walls draw over farther ones.
function southRuns(fp) {
  const set = footprintSet(fp);
  const byY = new Map();
  for (const key of set) {
    const c = key.indexOf(','); const x = +key.slice(0, c), y = +key.slice(c + 1);
    if (set.has(x + ',' + (y + 1))) continue;          // tile to the south → interior edge, not a front wall
    if (!byY.has(y)) byY.set(y, []); byY.get(y).push(x);
  }
  const runs = [];
  for (const [y, xs] of byY) {
    xs.sort((a, b) => a - b);
    let s = xs[0], p = xs[0];
    for (let i = 1; i < xs.length; i++) { if (xs[i] === p + 1) p = xs[i]; else { runs.push({ y, x0: s, x1: p + 1 }); s = p = xs[i]; } }
    runs.push({ y, x0: s, x1: p + 1 });
  }
  runs.sort((a, b) => a.y - b.y);
  return runs;
}

/** Draw the building's per-section south walls + aperture overlays. Returns true if drawn. */
export function drawBuildingTiles(ctx, b, camX, camY, tilePx, w, h) {
  if (typeof window !== 'undefined' && window._tileWalls === false) return false;
  const bb = b.footprint && b.footprint.boundingBox; if (!bb) return false;
  const mat = materialOf(b); if (!mat) return false;
  const D = getDIR(b.biome);
  const base = img(D + mat + '/ground_plain__v0.png'); if (!base) return false;
  const upper = img(D + mat + '/upper_plain__v0.png') || base;   // stackable storey (no foundation)
  const leftC = img(D + mat + '/ground_left_corner__v0.png') || img(D + mat + '/left_corner__v0.png');     // flat finished west end (+foundation)
  const rightC = img(D + mat + '/ground_right_corner__v0.png') || img(D + mat + '/right_corner__v0.png');  // flat finished east end (+foundation)
  const upperLeftC = img(D + mat + '/upper_left_corner__v0.png') || leftC;   // upper-storey end (no foundation)
  const upperRightC = img(D + mat + '/upper_right_corner__v0.png') || rightC;
  // PER-MATERIAL apertures: the real generated state tiles (4-tile-wide wall with the aperture baked in),
  // NOT a shared overlay or composited leaf. Door reaches the ground; window sits at its baked height.
  const doorTile = img(D + mat + '/ground_door__v0.png');
  const winTile = img(D + mat + '/ground_window__v0.png');
  // NO fallback to the GROUND window: it carries the foundation stone course, which would flash on the
  // upper floor while the upper tile async-loads (and the aperture is simply skipped until it's ready).
  const upperWinTile = img(D + mat + '/upper_window__v0.png');

  const t = tilePx;
  const wH = Math.round(t * WALL_CONFIG.wallHeight);                 // one storey = 4 tiles
  const WY = WALL_CONFIG.wallYOffset;
  const stories = Math.max(1, buildingFloors(b));
  const segW = Math.round(4 * t);                                   // base tile spans 4 tiles
  if (Math.round((b.x + bb.w) * t - camX) < 0 || Math.round(b.x * t - camX) > w) return true; // off-screen
  const fp = b.footprint;
  const runs = southRuns(fp);                                       // true outline → one wall per front run
  if (!runs.length) return true;
  const runGroundY = (y) => Math.round((b.y + y + 1) * t - camY) + Math.round(t * WY);

  ctx.imageSmoothingEnabled = false;
  // One FRONT-WALL SEGMENT per south-facing run, so L/T/round/courtyard footprints draw their real stepped
  // outline (mirror-tiled wall + finished end corners), not one bounding-box rectangle over empty notches.
  const drawRun = (left, right, groundY) => {
    for (let st = 0; st < stories; st++) {
      const tile = st === 0 ? base : upper;
      const top = groundY - (st + 1) * wH;
      if (top + wH < 0 || top > h) continue;
      // FINISHED END CORNERS provide the wall at the run's ends; the mirror-tiled BASE fills ONLY the gap
      // between them. CRUCIAL: the corner tile's OUTER edge is alpha-trimmed (transparent, so the world's
      // terrain shows past the building edge instead of a black outline). If the base wall were drawn UNDER
      // the corner, that opaque base would bleed through the corner's transparent edge (the "other texture
      // behind the column edge" bug). So inset the base by the corner width on each capped end.
      const lc = st === 0 ? leftC : upperLeftC;
      const rc = st === 0 ? rightC : upperRightC;
      const cw = Math.max(1, Math.min(segW, (right - left) / 2));
      const bL = lc ? left + cw : left;   // base starts after the left corner
      const bR = rc ? right - cw : right;  // base ends before the right corner
      // SYMMETRIC mirror-tiling: the per-segment flip is a PALINDROME about the run centre, so the wall reads
      // the same left↔right and its mirror-join "studs" land the same distance from each end (beside BOTH
      // flanking windows, not just one). Condition f(j) = !f(nSeg-1-j): even seg counts already alternate
      // symmetrically (NFNF); odd counts pivot on a centre tile (the building's centreline).
      const nSeg = Math.max(1, Math.ceil((bR - bL) / segW));
      const flipAt = (j) => { const m = nSeg - 1 - j; return j <= m ? (j % 2 === 1) : ((m % 2) !== 1); };
      let seg = 0;
      for (let x = bL; x < bR; x += segW) {
        const drawW = Math.min(segW, bR - x);
        ctx.save();
        ctx.beginPath(); ctx.rect(x, top, drawW, wH); ctx.clip();
        if (flipAt(seg)) { ctx.translate(x + segW, top); ctx.scale(-1, 1); ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, 0, 0, segW, wH); }
        else { ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, x, top, segW, wH); }
        ctx.restore();
        seg++;
      }
      // ground storey carries the foundation; upper storeys don't. Corner art scaled to cw; its OUTER edge
      // lands exactly at the run edge (left / right) so its alpha-trimmed outline reveals terrain.
      if (lc) { const sw = lc.naturalWidth * (cw / segW); ctx.drawImage(lc, 0, 0, sw, lc.naturalHeight, left, top, cw, wH); }
      if (rc) { const sw = rc.naturalWidth * (cw / segW); ctx.drawImage(rc, rc.naturalWidth - sw, 0, sw, rc.naturalHeight, right - cw, top, cw, wH); }
    }
  };
  for (const r of runs) drawRun(Math.round((b.x + r.x0) * t - camX), Math.round((b.x + r.x1) * t - camX), runGroundY(r.y));

  // PER-MATERIAL APERTURES — drawn on the run at the aperture's row, at that run's ground line (so apertures
  // sit on the correct stepped wall, not the bbox). Real generated state tiles, clipped to their span.
  const runFor = (ax, ay) => runs.find(r => r.y === ay && ax >= r.x0 && ax < r.x1) || runs[runs.length - 1];
  // CLAMP the aperture clip to the run's [left,right] pixel bounds so a door/window on the run's EDGE
  // tile (e.g. a guaranteed front door that lands on the easternmost south tile) draws ONLY within the
  // building frame instead of spilling ~0.8 tile past it and colliding with the corner tile.
  const drawAperture = (tile, cx, top, spanTiles, left, right) => {
    const clipW = Math.round(spanTiles * t);
    let cl = cx - clipW / 2, cr = cx + clipW / 2;
    if (left != null && cl < left) cl = left;
    if (right != null && cr > right) cr = right;
    if (cr <= cl) return;
    ctx.save();
    ctx.beginPath(); ctx.rect(cl, top, cr - cl, wH); ctx.clip();
    ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, cx - segW / 2, top, segW, wH);
    ctx.restore();
  };
  const runEdges = (r) => ({ left: Math.round((b.x + r.x0) * t - camX), right: Math.round((b.x + r.x1) * t - camX) });
  // DOORS — ground storey only. PROXIMITY DOOR ANIMATION: swing frame from player distance; fall back to
  // the closed static tile until that frame loads (frame 0 == closed == static tile).
  if (doorTile) for (const d of (fp.doors || [])) {
    const r = runFor(d.x, d.y);
    const gY = runGroundY(r.y);
    const { left, right } = runEdges(r);
    const fi = Math.round(doorOpenAmount(b, d) * (ANIM_FRAMES - 1));
    const frame = (fi > 0 && animFrame(b.biome, mat, 'door', fi)) || doorTile;
    drawAperture(frame, Math.round((b.x + d.x + 0.5) * t - camX), gY - wH, 2.6, left, right); // door span ~2.5 tiles, clamped to the run
  }
  // WINDOWS — on EVERY storey (stacked in vertical columns at each window x).
  for (const wn of (fp.windows || [])) {
    const r = runFor(wn.x, wn.y);
    const gY = runGroundY(r.y);
    const { left, right } = runEdges(r);
    const cx = Math.round((b.x + wn.x + 0.5) * t - camX);
    for (let st = 0; st < stories; st++) { const wt = st === 0 ? winTile : upperWinTile; if (wt) drawAperture(wt, cx, gY - (st + 1) * wH, 2.0, left, right); }
  }
  return true;
}
