// src/render/building-tiles.js — TILE-CORPUS wall renderer.
//
// Draws a building's SOUTH wall by MIRROR-tiling one base wall-tile per material (base·flip·base·flip…)
// across the footprint width, stacked per storey, with door/window OVERLAYS at the footprint's aperture
// tiles. The base tile (256px = 4 tiles wide × 4 tall @ 64px/tile, native alpha) is never modified, so
// walls are perfectly seamless + consistent. Routes through the same offscreen-canvas → GL scene FBO as
// the old wall path (drawBuildingTextured calls this, then the procedural roof). window._tileWalls flag.

import { WALL_CONFIG } from './wall-config.js';
import { buildingFloors } from './building-shadow.js';

const DIR = '/assets/pixelab/buildings/tiles/grassland/';
const _img = new Map();
function img(url) { let im = _img.get(url); if (!im) { im = new Image(); im.src = url; _img.set(url, im); } return (im.complete && im.naturalWidth) ? im : null; }

// Animation frames (full wall-with-aperture tiles, one per swing step) generated by animate_object and
// stored at <material>/anim/<kind>/frame_NNN.png. The door PLAYS on player proximity: far = frame 0
// (closed), near = last frame (open). Returns the frame image (or null until that frame loads).
const ANIM_FRAMES = 9;
function animFrame(mat, kind, idx) {
  return img(DIR + mat + '/anim/' + kind + '/frame_' + String(idx).padStart(3, '0') + '.png');
}
// 0 (closed, player far) → 1 (open, player at the door). World-tile distance ramp.
function doorOpenAmount(b, d) {
  const p = (typeof window !== 'undefined') && window._player;
  if (!p || typeof p.x !== 'number') return 0;
  const dist = Math.hypot((b.x + d.x + 0.5) - p.x, (b.y + d.y + 0.5) - p.y);
  const R_OPEN = 4.0, R_FULL = 1.5;   // starts opening at 4 tiles, fully open within 1.5
  return Math.max(0, Math.min(1, (R_OPEN - dist) / (R_OPEN - R_FULL)));
}

const MATERIALS = new Set(['timber_frame', 'fieldstone', 'cob', 'wattle_daub']);
function materialOf(b) {
  if (typeof window !== 'undefined' && window._tileMaterial) return window._tileMaterial;
  // wallSlug is already exactly one of the four grassland materials (assigned by the world gen),
  // so it maps directly to the tile folder. Unknown/other-biome slugs fall back to fieldstone.
  const s = ((b && b.wallSlug) || '').toLowerCase();
  return MATERIALS.has(s) ? s : 'fieldstone';
}
// Tile walls are the grassland corpus only — gate by (biome, wallSlug) exactly like the occluder's
// STRUCTURED_WALLS, so desert/snow/etc. buildings keep their own wall path instead of grassland walls.
export function isTiledBuilding(b) {
  if (typeof window !== 'undefined' && window._tileMaterial) return true; // console override forces it
  return !!(b && b.biome === 'grassland' && MATERIALS.has(((b.wallSlug) || '').toLowerCase()));
}
export function tileMaterialReady(b) { return !!img(DIR + materialOf(b) + '/ground_plain__v0.png'); }
export function hasTileWall(b) {
  if (typeof window !== 'undefined' && window._tileWalls === false) return false;
  return isTiledBuilding(b) && tileMaterialReady(b);
}

// Footprint tile set in LOCAL 0-based coords (matching the renderer's b.x+local / footprint.doors[].x
// convention). The building's actual shape lives in footprint.sections (rect/L/T/courtyard/round/...).
function footprintSet(fp) {
  const set = new Set();
  for (const s of (fp.sections || [])) for (let y = s.y0; y < s.y0 + s.h; y++) for (let x = s.x0; x < s.x0 + s.w; x++) set.add(x + ',' + y);
  return set;
}
// SOUTH-FACING perimeter runs: contiguous spans of tiles whose south neighbour is OUTSIDE the footprint.
// Each run is one visible front-wall segment, so the renderer draws the building's TRUE outline (an L/T/
// round building's stepped front) instead of one bounding-box rectangle. Sorted north→south so nearer
// (front) walls draw over farther ones.
function southRuns(fp) {
  const set = footprintSet(fp);
  const byY = new Map();
  for (const key of set) {
    const c = key.indexOf(','); const x = +key.slice(0, c), y = +key.slice(c + 1);
    if (set.has(x + ',' + (y + 1))) continue;          // tile to the south → interior edge, not a front wall
    if (!byY.has(y)) byY.set(y, []); byY.get(y).push(x);
  }
  const runs = [];
  for (const [y, xs] of byY) {
    xs.sort((a, b) => a - b);
    let s = xs[0], p = xs[0];
    for (let i = 1; i < xs.length; i++) { if (xs[i] === p + 1) p = xs[i]; else { runs.push({ y, x0: s, x1: p + 1 }); s = p = xs[i]; } }
    runs.push({ y, x0: s, x1: p + 1 });
  }
  runs.sort((a, b) => a.y - b.y);
  return runs;
}

/** Draw the building's per-section south walls + aperture overlays. Returns true if drawn. */
export function drawBuildingTiles(ctx, b, camX, camY, tilePx, w, h) {
  if (typeof window !== 'undefined' && window._tileWalls === false) return false;
  const bb = b.footprint && b.footprint.boundingBox; if (!bb) return false;
  const mat = materialOf(b);
  const base = img(DIR + mat + '/ground_plain__v0.png'); if (!base) return false;
  const upper = img(DIR + mat + '/upper_plain__v0.png') || base;   // stackable storey (no foundation)
  const leftC = img(DIR + mat + '/ground_left_corner__v0.png') || img(DIR + mat + '/left_corner__v0.png');     // flat finished west end (+foundation)
  const rightC = img(DIR + mat + '/ground_right_corner__v0.png') || img(DIR + mat + '/right_corner__v0.png');  // flat finished east end (+foundation)
  const upperLeftC = img(DIR + mat + '/upper_left_corner__v0.png') || leftC;   // upper-storey end (no foundation)
  const upperRightC = img(DIR + mat + '/upper_right_corner__v0.png') || rightC;
  // PER-MATERIAL apertures: the real generated state tiles (4-tile-wide wall with the aperture baked in),
  // NOT a shared overlay or composited leaf. Door reaches the ground; window sits at its baked height.
  const doorTile = img(DIR + mat + '/ground_door__v0.png');
  const winTile = img(DIR + mat + '/ground_window__v0.png');
  const upperWinTile = img(DIR + mat + '/upper_window__v0.png') || winTile;

  const t = tilePx;
  const wH = Math.round(t * WALL_CONFIG.wallHeight);                 // one storey = 4 tiles
  const WY = WALL_CONFIG.wallYOffset;
  const stories = Math.max(1, buildingFloors(b));
  const segW = Math.round(4 * t);                                   // base tile spans 4 tiles
  if (Math.round((b.x + bb.w) * t - camX) < 0 || Math.round(b.x * t - camX) > w) return true; // off-screen
  const fp = b.footprint;
  const runs = southRuns(fp);                                       // true outline → one wall per front run
  if (!runs.length) return true;
  const runGroundY = (y) => Math.round((b.y + y + 1) * t - camY) + Math.round(t * WY);

  ctx.imageSmoothingEnabled = false;
  // One FRONT-WALL SEGMENT per south-facing run, so L/T/round/courtyard footprints draw their real stepped
  // outline (mirror-tiled wall + finished end corners), not one bounding-box rectangle over empty notches.
  const drawRun = (left, right, groundY) => {
    for (let st = 0; st < stories; st++) {
      const tile = st === 0 ? base : upper;
      const top = groundY - (st + 1) * wH;
      if (top + wH < 0 || top > h) continue;
      let seg = 0;
      for (let x = left; x < right; x += segW) {
        const drawW = Math.min(segW, right - x);
        ctx.save();
        ctx.beginPath(); ctx.rect(x, top, drawW, wH); ctx.clip();
        if (seg % 2 === 1) { ctx.translate(x + segW, top); ctx.scale(-1, 1); ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, 0, 0, segW, wH); }
        else { ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, x, top, segW, wH); }
        ctx.restore();
        seg++;
      }
      // FINISHED END CORNERS at this run's ends (ground storey carries the foundation; upper storeys don't).
      const lc = st === 0 ? leftC : upperLeftC;
      const rc = st === 0 ? rightC : upperRightC;
      if (lc || rc) {
        const cw = Math.max(1, Math.min(segW, (right - left) / 2));
        if (lc) { const sw = lc.naturalWidth * (cw / segW); ctx.drawImage(lc, 0, 0, sw, lc.naturalHeight, left, top, cw, wH); }
        if (rc) { const sw = rc.naturalWidth * (cw / segW); ctx.drawImage(rc, rc.naturalWidth - sw, 0, sw, rc.naturalHeight, right - cw, top, cw, wH); }
      }
    }
  };
  for (const r of runs) drawRun(Math.round((b.x + r.x0) * t - camX), Math.round((b.x + r.x1) * t - camX), runGroundY(r.y));

  // PER-MATERIAL APERTURES — drawn on the run at the aperture's row, at that run's ground line (so apertures
  // sit on the correct stepped wall, not the bbox). Real generated state tiles, clipped to their span.
  const runFor = (ax, ay) => runs.find(r => r.y === ay && ax >= r.x0 && ax < r.x1) || runs[runs.length - 1];
  const drawAperture = (tile, cx, top, spanTiles) => {
    const clipW = Math.round(spanTiles * t);
    ctx.save();
    ctx.beginPath(); ctx.rect(cx - clipW / 2, top, clipW, wH); ctx.clip();
    ctx.drawImage(tile, 0, 0, tile.naturalWidth, tile.naturalHeight, cx - segW / 2, top, segW, wH);
    ctx.restore();
  };
  // DOORS — ground storey only. PROXIMITY DOOR ANIMATION: swing frame from player distance; fall back to
  // the closed static tile until that frame loads (frame 0 == closed == static tile).
  if (doorTile) for (const d of (fp.doors || [])) {
    const gY = runGroundY(runFor(d.x, d.y).y);
    const fi = Math.round(doorOpenAmount(b, d) * (ANIM_FRAMES - 1));
    const frame = (fi > 0 && animFrame(mat, 'door', fi)) || doorTile;
    drawAperture(frame, Math.round((b.x + d.x + 0.5) * t - camX), gY - wH, 2.6); // door span ~2.5 tiles
  }
  // WINDOWS — on EVERY storey (stacked in vertical columns at each window x).
  for (const wn of (fp.windows || [])) {
    const gY = runGroundY(runFor(wn.x, wn.y).y);
    const cx = Math.round((b.x + wn.x + 0.5) * t - camX);
    for (let st = 0; st < stories; st++) { const wt = st === 0 ? winTile : upperWinTile; if (wt) drawAperture(wt, cx, gY - (st + 1) * wH, 2.0); }
  }
  return true;
}
