// AUTO-GENERATED by scripts/gen-dressing-vmap.mjs — do not edit.
// Re-run whenever _dressing_curation.json changes or new base__vN.png sprites land on disk.
export const DRESSING_ALLOWED = {
 "dense_forest/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "dense_forest/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "desert/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "desert/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "desert/fringed_shop_canopy": [
  2,
  3,
  5,
  6
 ],
 "desert/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "desert/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "desert/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "desert/sand_texture": [
  0
 ],
 "desert/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "desert/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "desert/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "desert/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "desert/vine_fork": [
  0
 ],
 "desert/vine_leaf_cluster": [
  0
 ],
 "desert/vine_root_base": [
  0
 ],
 "desert/vine_segment": [
  0
 ],
 "desert/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "desert/wood_slat_awning": [
  4,
  5,
  6,
  7
 ],
 "desert/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "forest/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "forest/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "forest/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "forest/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "forest/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "forest/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "forest/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "forest/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "forest/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "forest/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "forest/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "forest/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "forest/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "grassland/board_batten_shutter": [
  0,
  1
 ],
 "grassland/carved_timber_bracket": [
  0,
  1
 ],
 "grassland/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "grassland/d1_board_patch": [
  0,
  1,
  2,
  3
 ],
 "grassland/d1_plank_gap": [
  0,
  1,
  2,
  3
 ],
 "grassland/door_handle_latch": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/door_knocker": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/door_nameplate": [
  0,
  1
 ],
 "grassland/door_wreath": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/festoon_garland": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "grassland/heraldic_banner": [
  0,
  1,
  2
 ],
 "grassland/iron_candle_lantern": [
  0,
  1,
  2
 ],
 "grassland/louvred_shutter": [
  2,
  3
 ],
 "grassland/projecting_board_sign": [
  0,
  1,
  2,
  3,
  4,
  5
 ],
 "grassland/strung_festival_lights": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/swinging_trade_sign": [
  0,
  1,
  2
 ],
 "grassland/terracotta_wall_planter": [
  0,
  1
 ],
 "grassland/timber_flower_box": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/triangle_bunting": [
  0,
  1,
  2,
  3,
  4,
  5,
  6
 ],
 "grassland/vine_fork": [
  0,
  1,
  2,
  3
 ],
 "grassland/vine_root_base": [
  0,
  1,
  2,
  3
 ],
 "grassland/vine_segment": [
  0,
  1,
  2,
  3
 ],
 "grassland/wall_oil_lamp": [
  0,
  1,
  2
 ],
 "grassland/wood_slat_awning": [
  5,
  6
 ],
 "grassland/wrought_iron_bracket": [
  0,
  1
 ],
 "grassland/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3,
  4,
  5
 ],
 "hills/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "hills/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "hills/fringed_shop_canopy": [
  2,
  3,
  4
 ],
 "hills/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "hills/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "hills/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "hills/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "hills/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "hills/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "hills/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "hills/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "hills/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "hills/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "mountains/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "mountains/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "mountains/fringed_shop_canopy": [
  1,
  2,
  3,
  4
 ],
 "mountains/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "mountains/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "mountains/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "mountains/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "mountains/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "mountains/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "mountains/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "mountains/vine_fork": [
  0
 ],
 "mountains/vine_leaf_cluster": [
  0
 ],
 "mountains/vine_root_base": [
  0
 ],
 "mountains/vine_segment": [
  0
 ],
 "mountains/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "mountains/wood_slat_awning": [
  4,
  5,
  6,
  7
 ],
 "mountains/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "mystic/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "mystic/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "mystic/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "mystic/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "mystic/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "mystic/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "mystic/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "mystic/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "mystic/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "mystic/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "mystic/vine_fork": [
  0
 ],
 "mystic/vine_leaf_cluster": [
  0
 ],
 "mystic/vine_root_base": [
  0
 ],
 "mystic/vine_segment": [
  0
 ],
 "mystic/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "mystic/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "mystic/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "savanna/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "savanna/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "savanna/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "savanna/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "savanna/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "savanna/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "savanna/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "savanna/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "savanna/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "savanna/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "savanna/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "savanna/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "savanna/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "steppe/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "steppe/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "steppe/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "steppe/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "steppe/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "steppe/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "steppe/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "steppe/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "steppe/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "steppe/triangle_bunting": [
  4,
  6
 ],
 "steppe/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "steppe/wood_slat_awning": [
  4,
  5,
  7
 ],
 "steppe/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "taiga/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "taiga/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "taiga/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "taiga/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "taiga/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "taiga/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "taiga/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "taiga/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "taiga/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "taiga/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "taiga/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "taiga/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "taiga/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "tropical_forest/vine_fork": [
  0
 ],
 "tropical_forest/vine_leaf_cluster": [
  0
 ],
 "tropical_forest/vine_root_base": [
  0
 ],
 "tropical_forest/vine_segment": [
  0
 ],
 "tundra/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "tundra/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "tundra/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "tundra/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "tundra/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "tundra/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "tundra/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "tundra/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "tundra/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "tundra/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "tundra/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "tundra/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "tundra/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ],
 "volcanic/cloth_market_awning": [
  0,
  1,
  2,
  3
 ],
 "volcanic/festoon_garland": [
  0,
  1,
  2,
  3
 ],
 "volcanic/fringed_shop_canopy": [
  0,
  1,
  2,
  3
 ],
 "volcanic/heraldic_banner": [
  0,
  1,
  2,
  3
 ],
 "volcanic/iron_candle_lantern": [
  0,
  1,
  2,
  3
 ],
 "volcanic/projecting_board_sign": [
  0,
  1,
  2,
  3
 ],
 "volcanic/strung_festival_lights": [
  0,
  1,
  2,
  3
 ],
 "volcanic/swinging_trade_sign": [
  0,
  1,
  2,
  3
 ],
 "volcanic/timber_flower_box": [
  0,
  1,
  2,
  3
 ],
 "volcanic/triangle_bunting": [
  0,
  1,
  2,
  3
 ],
 "volcanic/vine_fork": [
  0
 ],
 "volcanic/vine_root_base": [
  0
 ],
 "volcanic/vine_segment": [
  0
 ],
 "volcanic/wall_oil_lamp": [
  0,
  1,
  2,
  3
 ],
 "volcanic/wood_slat_awning": [
  0,
  1,
  2,
  3
 ],
 "volcanic/wrought_iron_silhouette_sign": [
  0,
  1,
  2,
  3
 ]
};
