// AUTO-GENERATED by scripts/gen-mf-catalog.mjs — do not edit.
// Regenerate as F5 state art / animations land on disk.
export var MO_CATALOG = {
 "arctic": [
  {
   "name": "frozen_ruin",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "ice_formation",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "snow_drift_mound",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "beach": [
  {
   "name": "anchor_relic",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "beached_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "tide_pool_rock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "dense_forest": [
  {
   "name": "hollow_stump",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "root_mound",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "rotting_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "desert": [
  {
   "name": "bleached_skull",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "clay_pot_shard",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "sandstone_formation",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "forest": [
  {
   "name": "fallen_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "mossy_boulder",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "tree_stump",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "grassland": [
  {
   "name": "fence_post",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "field_boulder",
   "size": 96,
   "variants": 64,
   "states": {
    "burned": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ],
    "cracked": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ],
    "destroyed": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ],
    "enchanted": [
     0,
     7,
     14,
     21
    ],
    "frozen": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ],
    "mossy_overgrown": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ]
   },
   "anims": []
  },
  {
   "name": "hay_bale",
   "size": 96,
   "variants": 64,
   "states": {
    "burned": [
     0,
     7,
     14,
     21
    ],
    "cracked": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49,
     56
    ],
    "destroyed": [
     0,
     7,
     14,
     21,
     28,
     35,
     42,
     49
    ],
    "mossy_overgrown": [
     0,
     7,
     14,
     21
    ]
   },
   "anims": []
  }
 ],
 "hills": [
  {
   "name": "granite_outcrop",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "old_milestone",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "stone_pile",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "mountains": [
  {
   "name": "cliff_fragment",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "frozen_cairn",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "ice_boulder",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "mystic": [
  {
   "name": "ancient_altar",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "crystal_cluster",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "rune_stone",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "savanna": [
  {
   "name": "bone_pile",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "dry_well",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "termite_mound",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "steppe": [
  {
   "name": "buried_post",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "stone_cairn",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "wind_rock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "swamp": [
  {
   "name": "bog_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "mud_mound",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "rotting_dock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "taiga": [
  {
   "name": "frost_stump",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "ice_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "snow_rock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "tropical_forest": [
  {
   "name": "buttress_root",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "jungle_rock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "vine_log",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "tundra": [
  {
   "name": "frozen_bones",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "ice_boulder",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "permafrost_mound",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ],
 "volcanic": [
  {
   "name": "basalt_column",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "lava_rock",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  },
  {
   "name": "obsidian_pillar",
   "size": 96,
   "variants": 64,
   "states": {},
   "anims": []
  }
 ]
};
